services:
  # kafka:
  #   image: docker.io/bitnami/kafka:3.9
  #   ports:
  #     - '9094:9094'
  #   restart: unless-stopped
  #   environment:
  #     - KAFKA_CFG_NODE_ID=0
  #     - KAFKA_CFG_PROCESS_ROLES=controller,broker
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
  #     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  # redis:
  #   image: docker.io/bitnami/redis:7.4
  #   container_name: redis
  #   environment:
  #     # ALLOW_EMPTY_PASSWORD is recommended only for development.
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  #   ports:
  #     - '6379:6379'

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/dev-prom.yaml'
  #   ports:
  #      - 9090:9090
  #   restart: unless-stopped
  #   volumes:
  #     - ./../metric/dev:/etc/prometheus

  # jaeger:
  #   image: jaegertracing/all-in-one:1.60
  #   container_name: jaeger
  #   environment:
  #     - COLLECTOR_OTLP_ENABLED=true
  #   hostname: jaeger
  #   ports:
  #     - 16686:16686
  #   #   - 4317:4317
  #   #   - 4318:4318
  #   #   - 14268:14268
  #   restart: unless-stopped

  timeline-service:
    # depends_on:
    #   jaeger:
    #     condition: service_started
    #   prometheus:
    #     condition: service_started
    #   kafka:
    #     condition: service_started
    #   redis:
    #     condition: service_started
    image: ${IMAGE}
    container_name: timeline-service
    environment:
      CONSUMER_KAFKA_BROKERS: kafka:9092
      REDIS_ADDRS: redis:6379
      REDIS_ENABLE_TRACING: true
      POST_SERVICE_URI: post-service:3001
      RELATION_SERVICE_URI: relation-service:3002
      OTLP_PROBABILITY: 1
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_EXPORTER_OTLP_INSECURE: true
      LOG_LEVEL: debug
    restart: unless-stopped